name: Reading List
favicon: null
layout_spectrum: 0.613684854703024
typography_spectrum: 0.7323744234163314
title: My Reading List
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.634773850440979
  lightness: 0.02569738356396556
  saturation: 0.46992600499652326
  rhythmicContrast: 0.7535006054677069
purpose: []
